name: Self-Hosted Runner Check

on:
  workflow_dispatch:

jobs:
  check-runner:
    name: Check Self-Hosted Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Script Executable
        run: |
          cd 
          chmod +x .github/workflows/check_runner.sh

      - name: Run Bash Script
        run: .github/workflows/check_runner.sh
